# -*- coding: utf-8 -*-
"""fcc-MAGIC-example

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xz54_4KtJfB85aTzV2ArwhTKBw5Vku-g
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""DATASET: EXAMPLE
LINK: https://youtu.be/i_LwzRVP7bg?si=s4DSOp7DsW8Vvs3r
"""

cols = ["fLength","fWidth","fSize","fConc","fConc1","fAsym","fM3Long","fM3Trans","fAlpha","fDist","class"]
df = pd.read_csv("magic04.data",names=cols)
df.head()

df["class"].unique()

